#yml格式配置文档范例
server:
  #端口配置
  port: 8080
  #上下文
  servlet:
    context-path: /usersys
#数据源配置
spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Springboot2.0 的hikari配置
    hikari:
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      #连接池最大连接数，默认是10
      maximum-pool-size: 10
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      #连接池名称
      pool-name: MyHikariCP
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect ,注意这个是不支持事务的方言。
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        #配置懒加载策略
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update

mybatis-plus:
  pager_size: 10

debug: true